Document: quadrisc
Title: Debian quadrisc Manual
Author: <insert document author here>
Abstract: This manual describes what quadrisc is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/quadrisc/quadrisc.sgml.gz

Format: postscript
Files: /usr/share/doc/quadrisc/quadrisc.ps.gz

Format: text
Files: /usr/share/doc/quadrisc/quadrisc.text.gz

Format: HTML
Index: /usr/share/doc/quadrisc/html/index.html
Files: /usr/share/doc/quadrisc/html/*.html
